services:

  server:
    container_name: finalproject
    depends_on:
      - mongodb
    build: 
      context: ./server
      target: prod
    restart: always
    env_file: ./.env
    ports:
      - 8080:8080
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=27017
    stdin_open: true
    tty: true

  mongodb:
    image: "mongo:6.0.2"
    restart: unless-stopped
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    volumes:
      - db:/data/db

volumes:
  db: