services:

  backend:
    container_name: finalproject-backend
    depends_on:
      - mongodb
    build: 
      context: ./backend
      target: debug
    env_file: ./.env
    ports:
      - 9229:9229
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=27017
      - NODE_ENV=development
    networks:
      - public
      - private
    volumes:
      - ./backend:/work
      - /work/node_modules

  frontend:
    container_name: finalproject-frontend
    depends_on:
      - backend
    build:
      context: ./frontend
    ports:
      - 80:80
    networks:
      - public
    volumes:
      - ./frontend:/work

  mongodb:
    image: "mongo:6.0.2"
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    volumes:
      - db:/data/db
      - configdb:/data/configdb
    networks:
      - private

  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGODB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGODB_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongodb:27017/
    networks:
      - private

networks:
  public:
  private:
volumes:
  db:
  configdb:
