services:

  backend:
    container_name: finalproject-backend
    depends_on:
      - mongo
    build:
      context: ./app
      target: debug
    env_file: ./.env
    ports:
      - 8080:8080
      - 9229:9229
    environment:
      - TWITTER_BEARER_TOKEN=$TWITTER_BEARER_TOKEN
      - DB_HOST=mongo
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=27017
      - NODE_ENV=development
    volumes:
      - ./app:/work
      - /work/node_modules

  mongo:
    image: "mongo:6.0.2"
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    volumes:
      - db:/data/db
      - configdb:/data/configdb

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGODB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGODB_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongo:27017/

volumes:
  db:
  configdb:
