services:

  backend:
    container_name: finalproject-backend
    depends_on:
      - mongo
    build:
      context: ./app
      target: prod
    env_file: ./.env
    ports:
      - 8080:8080
    environment:
      - TWITTER_BEARER_TOKEN=$TWITTER_BEARER_TOKEN
      - DB_HOST=mongo
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=27017

  mongo:
    image: "mongo:6.0.2"
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    volumes:
      - db:/data/db
      - configdb:/data/configdb

volumes:
  db:
  configdb:
