services:

  backend:
    container_name: finalproject-backend
    depends_on:
      - mongo
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: prod
    env_file: ./.env
    environment:
      - DB_HOST=mongo
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=27017
    networks:
      - public
      - private

  frontend:
    container_name: finalproject-frontend
    depends_on:
      - backend
    build:
      context: ./frontend
      target: prod
    ports:
      - 80:80
    networks:
      - public

  mongo:
    image: "mongo:6.0.2"
    env_file: ./.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGODB_USER
      MONGO_INITDB_ROOT_PASSWORD: $MONGODB_PASSWORD
    volumes:
      - db:/data/db
      - configdb:/data/configdb
    networks:
      - private

networks:
  public:
  private:
volumes:
  db:
  configdb:
