services:

  server:
    container_name: finalproject
    build: 
      context: ./server
      target: debug
    restart: always
    env_file: ./.env
    ports:
      - 8080:8080
      - 9229:9229
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=27017
      - NODE_ENV=development
    stdin_open: true
    tty: true
    volumes:
      - ./server:/code
      - /code/node_modules

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGODB_USER
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGODB_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGODB_USER:$MONGODB_PASSWORD@mongodb:27017/
